/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function topColours(path: string): Promise<unknown>
export function topColors(path: string): Promise<unknown>
export function topColoursHex(path: string): Promise<unknown>
export function topColorsHex(path: string): Promise<unknown>
